/* SPDX-License-Identifier: GPL-3.0-or-later
   SPDX-FileCopyrightText: Copyright © 2023 Erez Geva <ErezGeva2@gmail.com> */

#include <gtest/gtest.h>
#define ST_USE_C
#include "nsl_statistics.h"

TEST(nslCTest, stat)
{
    struct nsl_stats s0, *s = &s0;
    nsl_stats_init(s);
    EXPECT_EQ(nsl_stats_get_num_elems(s), 0);
    EXPECT_EQ(nsl_stats_get_min(s), 0x7FFFFFFFFFFFFFFFLL);
    EXPECT_EQ(nsl_stats_get_max(s), -0x8000000000000000LL);
    EXPECT_EQ(nsl_stats_get_mean(s), 0);
    EXPECT_DOUBLE_EQ(nsl_stats_get_sq(s), 0);
    EXPECT_DOUBLE_EQ(nsl_stats_get_sd(s), 0);
    nsl_stats_add_elem(s, 10);
    EXPECT_EQ(nsl_stats_get_num_elems(s), 1);
    EXPECT_EQ(nsl_stats_get_min(s), 10);
    EXPECT_EQ(nsl_stats_get_max(s), 10);
    EXPECT_EQ(nsl_stats_get_mean(s), 10);
    EXPECT_DOUBLE_EQ(nsl_stats_get_sq(s), 100);
    EXPECT_TRUE(std::isnan(nsl_stats_get_sd(s)));
    nsl_stats_add_elem(s, 20);
    EXPECT_EQ(nsl_stats_get_num_elems(s), 2);
    EXPECT_EQ(nsl_stats_get_min(s), 10);
    EXPECT_EQ(nsl_stats_get_max(s), 20);
    EXPECT_EQ(nsl_stats_get_mean(s), 15);
    EXPECT_DOUBLE_EQ(nsl_stats_get_sq(s), 250);
    EXPECT_DOUBLE_EQ(nsl_stats_get_sd(s), 7.0710678118654755);
    nsl_stats_add_elem(s, 30);
    EXPECT_EQ(nsl_stats_get_num_elems(s), 3);
    EXPECT_EQ(nsl_stats_get_min(s), 10);
    EXPECT_EQ(nsl_stats_get_max(s), 30);
    EXPECT_EQ(nsl_stats_get_mean(s), 20);
    EXPECT_DOUBLE_EQ(nsl_stats_get_sq(s), 466.66666666666669);
    EXPECT_DOUBLE_EQ(nsl_stats_get_sd(s), 10);
}
TEST(nslCTest, vec)
{
    struct nsl_vec_stats v0, *v = &v0;
    nsl_vec_stats_init(v, 10,5,10);
    EXPECT_EQ(nsl_vec_stats_get_start(v), 10);
    EXPECT_EQ(nsl_vec_stats_get_end(v), 60);
    EXPECT_EQ(nsl_vec_stats_get_step(v), 10);
    EXPECT_EQ(nsl_vec_stats_get_size(v), 5);
    // add elements
    EXPECT_EQ(nsl_vec_stats_get_below(v), 0);
    EXPECT_EQ(nsl_vec_stats_get_above(v), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 0), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 10), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 20), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 30), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 40), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 50), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 60), 0);
    nsl_vec_stats_add_elem(v, 9);
    EXPECT_EQ(nsl_vec_stats_get_below(v), 1);
    EXPECT_EQ(nsl_vec_stats_get_above(v), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 0), 1);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 10), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 20), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 30), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 40), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 50), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 60), 0);
    nsl_vec_stats_add_elem(v, 10);
    EXPECT_EQ(nsl_vec_stats_get_below(v), 1);
    EXPECT_EQ(nsl_vec_stats_get_above(v), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 0), 1);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 10), 1);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 20), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 30), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 40), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 50), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 60), 0);
    nsl_vec_stats_add_elem(v, 19);
    EXPECT_EQ(nsl_vec_stats_get_below(v), 1);
    EXPECT_EQ(nsl_vec_stats_get_above(v), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 0), 1);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 10), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 20), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 30), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 40), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 50), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 60), 0);
    nsl_vec_stats_add_elem(v, 20);
    EXPECT_EQ(nsl_vec_stats_get_below(v), 1);
    EXPECT_EQ(nsl_vec_stats_get_above(v), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 0), 1);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 10), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 20), 1);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 30), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 40), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 50), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 60), 0);
    nsl_vec_stats_add_elem(v, 29);
    EXPECT_EQ(nsl_vec_stats_get_below(v), 1);
    EXPECT_EQ(nsl_vec_stats_get_above(v), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 0), 1);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 10), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 20), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 30), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 40), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 50), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 60), 0);
    nsl_vec_stats_add_elem(v, 30);
    EXPECT_EQ(nsl_vec_stats_get_below(v), 1);
    EXPECT_EQ(nsl_vec_stats_get_above(v), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 0), 1);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 10), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 20), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 30), 1);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 40), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 50), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 60), 0);
    nsl_vec_stats_add_elem(v, 39);
    EXPECT_EQ(nsl_vec_stats_get_below(v), 1);
    EXPECT_EQ(nsl_vec_stats_get_above(v), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 0), 1);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 10), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 20), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 30), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 40), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 50), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 60), 0);
    nsl_vec_stats_add_elem(v, 40);
    EXPECT_EQ(nsl_vec_stats_get_below(v), 1);
    EXPECT_EQ(nsl_vec_stats_get_above(v), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 0), 1);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 10), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 20), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 30), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 40), 1);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 50), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 60), 0);
    nsl_vec_stats_add_elem(v, 49);
    EXPECT_EQ(nsl_vec_stats_get_below(v), 1);
    EXPECT_EQ(nsl_vec_stats_get_above(v), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 0), 1);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 10), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 20), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 30), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 40), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 50), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 60), 0);
    nsl_vec_stats_add_elem(v, 50);
    EXPECT_EQ(nsl_vec_stats_get_below(v), 1);
    EXPECT_EQ(nsl_vec_stats_get_above(v), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 0), 1);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 10), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 20), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 30), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 40), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 50), 1);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 60), 0);
    nsl_vec_stats_add_elem(v, 59);
    EXPECT_EQ(nsl_vec_stats_get_below(v), 1);
    EXPECT_EQ(nsl_vec_stats_get_above(v), 0);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 0), 1);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 10), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 20), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 30), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 40), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 50), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 60), 0);
    nsl_vec_stats_add_elem(v, 60);
    EXPECT_EQ(nsl_vec_stats_get_below(v), 1);
    EXPECT_EQ(nsl_vec_stats_get_above(v), 1);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 0), 1);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 10), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 20), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 30), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 40), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 50), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v, 60), 1);
    // Copy vector
    struct nsl_vec_stats v02, *v2 = &v02;
	nsl_vec_stats_copy(v2, v);
    EXPECT_EQ(nsl_vec_stats_get_start(v2), 10);
    EXPECT_EQ(nsl_vec_stats_get_end(v2), 60);
    EXPECT_EQ(nsl_vec_stats_get_step(v2), 10);
    EXPECT_EQ(nsl_vec_stats_get_size(v2), 5);
    EXPECT_EQ(nsl_vec_stats_get_below(v2), 1);
    EXPECT_EQ(nsl_vec_stats_get_above(v2), 1);
    EXPECT_EQ(nsl_vec_stats_get_value(v2, 0), 1);
    EXPECT_EQ(nsl_vec_stats_get_value(v2, 10), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v2, 20), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v2, 30), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v2, 40), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v2, 50), 2);
    EXPECT_EQ(nsl_vec_stats_get_value(v2, 60), 1);
    nsl_vec_stats_remove(v);
    nsl_vec_stats_remove(v2);
}
